[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/products/*"
  to = "/.netlify/functions/products/:splat"
  status = 200

[[redirects]]
  from = "/api/products"
  to = "/.netlify/functions/products"
  status = 200

[[redirects]]
  from = "/api/admin/*"
  to = "/.netlify/functions/admin/:splat"
  status = 200
